# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" "nvidia" ];
    boot.blacklistedKernelModules = ["nouveau"];
    boot.extraModprobeConfig = "options snd-hda-intel probe_mask=1";

    fileSystems."/" =
        { device = "/dev/disk/by-label/nixos";
          fsType = "ext4";
        };

    fileSystems."/boot" =
        { device = "/dev/disk/by-label/boot";
          fsType = "vfat";
        };

    swapDevices = [ ];

    hardware.pulseaudio.enable = true;

    powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
