# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a799ff42-a7a0-4eca-b6da-5742e48e1260";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/626D-7B4A";
      fsType = "vfat";
    };
  fileSystems."/srv/finance" =
    { device = "/dev/disk/by-label/external0";
      fsType = "btrfs";
    };
  fileSystems."/srv/mail" =
    { device = "/dev/disk/by-label/external0";
      fsType = "btrfs";
    };
  fileSystems."/srv/restic" =
    { device = "/dev/disk/by-label/external0";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/245c3193-8ac7-4dca-a164-bfad2cb8ce89"; }
    ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.pulseaudio.enable = true;
  
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
